name: Maven Deploy
description: "Deploys a Maven package to a repository."

runs:
  using: composite
  steps:
    - name: "Echo Variables"
      run: |
        echo "repository-url: ${{ secrets.REPOSITORY_URL }}"
        echo "user: ${{ secrets.CAP_DEPLOYMENT_USER }}"
        echo "password: ${{ secrets.CAP_DEPLOYMENT_PASS }}"
        echo "pom-file: ${{ inputs.pom-file }}"
      shell: bash

    - name: "Setup java"
      uses: actions/setup-java@v4
      with:
        distribution: 'sapmachine'
        java-version: '17'
        server-id: REPOSITORY_URL
        server-username: CAP_DEPLOYMENT_USER
        server-password: CAP_DEPLOYMENT_PASS

    - name: "Publish package"
      run: >
        mvn 
        --batch-mode
        --no-transfer-progress
        --fail-at-end
        --threads 1C
        -Durl=${{ inputs.repository-url }}
        -DrepositoryId=${{ inputs.server-id }}
        -Dmaven.install.skip=true
        -Dmaven.test.skip=true
        -Dmaven.compiler.showCompilationChanges
        -Dhttp.keepAlive=false
        -DskipDuringDeploy=true
        -f ${{ inputs.pom-file }}
        deploy
      #env:
        #DEPLOYMENT_USER: ${{ inputs.user }}
        #DEPLOYMENT_PASS: ${{ inputs.password }}

      env:
          CAP_DEPLOYMENT_USER: ${{ secrets.CAP_DEPLOYMENT_USER }}
          CAP_DEPLOYMENT_PASS: ${{ secrets.CAP_DEPLOYMENT_PASS }}
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
      
      shell: bash
