name: Java Build with Maven

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven Custom Action
        uses: ./.github/actions/build

  deploy-snapshot:
    name: Deploy snapshot to Artifactory
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: sapmachine
          cache: maven
          server-id: artifactory
          server-username: CAP_DEPLOYMENT_USER
          server-password: CAP_DEPLOYMENT_PASS

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.6.3

      - name: Get Revision
        id: get-revision
        run: |
          echo "REVISION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Print Revision
        run: echo "Current revision ${{ steps.get-revision.outputs.REVISION }}"
        shell: bash
  
      - name: Deploy snapshot
        if: ${{ endsWith(steps.get-revision.outputs.REVISION, '-SNAPSHOT') }}
        # https://maven.apache.org/plugins/maven-deploy-plugin/usage.html#the-deploy-deploy-mojo
        run: |
          mvn -B -ntp -fae -Dmaven.install.skip=true -Dmaven.test.skip=true -DdeployAtEnd=true deploy
        env:
          CAP_DEPLOYMENT_USER: ${{ secrets.CAP_DEPLOYMENT_USER }}
          CAP_DEPLOYMENT_PASS: ${{ secrets.CAP_DEPLOYMENT_PASS }}
        shell: bash
